Repository Software-Meister-High-School-Community/MOIZA-Front-V1, pull requests merged in 2022-06, with the labels that each got.

#28 🔀:: (#27) 404 페이지 추가
  src/components/common/button/submitButton/index.tsx
  src/components/common/form/noticeForm.tsx
  src/components/common/seeMoreModal/index.tsx
  src/components/editProfile/backgroundColor.tsx
  src/components/follow/constant.ts
  src/components/follow/followCard.tsx
  src/components/follow/followList.tsx
  src/components/follow/followListType.tsx
  src/components/follow/index.tsx
  src/components/follow/userList/index.tsx
  src/components/follow/userList/styles.ts
  src/components/mypage/index.tsx
  src/components/mypage/postList/index.tsx
  src/components/mypage/profile/index.tsx
  src/components/mypage/profile/styles.ts
  src/components/mypage/styles.ts
  src/components/post/postReply/PostComment/index.tsx
  src/components/post/postReply/PostReplyCommentOfComment/PostReplyCOCForm/index.tsx
  src/components/post/postReply/index.tsx
  src/hooks/user/useUserInfo.ts
  src/pages/404.tsx
  src/pages/follow/index.tsx
  src/pages/mypage/index.tsx
  src/pages/profile/index.tsx
  src/router.tsx
  src/store/follow/followOwner.ts
  src/style/styled.d.ts
  src/utils/api/follow/index.ts
  src/utils/function/isValidUrl.ts
Labels: 기능 추가

#39 🔀 :: (#34) mod bug add components
  package.json
  public/index.html
  src/assets/img/introduce/puzzle.svg
  src/components/common/button/heartButton/style.ts
  src/components/main/menu/constant.ts
  src/components/main/menu/noticemenu/index.tsx
  src/components/main/menu/noticemenu/style.ts
  src/components/main/menu/starmenu/StarMenu.tsx
  src/components/main/menu/starmenu/StarPost.tsx
  src/components/main/menu/starmenu/style.ts
  src/components/main/slide/index.tsx
  src/router.tsx
  yarn.lock
Labels: Chore, 기능 추가

#35 🔀:: (#33) 마이페이지 예외처리 및 코드 수정
  src/components/header/index.tsx
  src/components/mypage/index.tsx
  src/components/mypage/postList/index.tsx
  src/components/mypage/profile/index.tsx
  src/pages/mypage/index.tsx
  src/pages/profile/index.tsx
  src/router.tsx
Labels: 기능 추가, 리펙토링

#42 🔀:: (#38) 프로필편집 페이지 api 연결 및 코드 수정
  src/components/editProfile/changeUserProfile.tsx
  src/components/editProfile/changeUserType.tsx
  src/components/editProfile/index.tsx
  src/components/editProfile/introduction.tsx
  src/components/editProfile/link.tsx
  src/models/default/request.ts
  src/models/users/request.ts
  src/pages/editProfile/index.tsx
Labels: 기능 추가, 리펙토링

#37 🔀:: (#36) 팔로우관련 예외처리 및 코드 수정
  src/components/follow/index.tsx
  src/hooks/useException.tsx
  src/pages/follow/index.tsx
Labels: 기능 추가, 리펙토링

#41 🔀:: (#40) 메인페이지 api 연결 (인기게시물,공지사항)
  src/components/main/menu/noticemenu/NoticeItem.tsx
  src/components/main/menu/noticemenu/index.tsx
  src/components/main/menu/noticemenu/style.ts
  src/components/main/menu/starmenu/StarMenu.tsx
  src/components/main/menu/starmenu/StarPost.tsx
  src/models/feeds/response.ts
Labels: 기능 추가, 리펙토링

#47 🔀:: (#46) 모바일에서 웹사이트 접속시 보여줄 페이지 추가
  package.json
  src/App.tsx
  src/assets/img/MOIZALogo/koreanHorizontalType.svg
  src/assets/img/MOIZALogo/koreanHorizontalType.tsx
  src/assets/img/MOIZALogo/moizaBlack.svg
  src/assets/img/default/emptyHeart.svg
  src/assets/img/default/smallWhiteProfile.svg
  src/components/introduce/index.tsx
  src/pages/isMobileAccess.tsx
  yarn.lock
Labels: 기능 추가

#48 🔀 :: (#45) notice api settings
  src/components/.gitkeep
  src/components/notice/noticePost/index.tsx
  src/components/notice/noticePost/style.ts
  src/components/notice/noticelist/index.tsx
  src/components/notice/shownotice/index.tsx
Labels: Chore, 기능 추가

#54 🔀 :: (#53) 메인페이지 banner 수정
  src/assets/img/banner/광주.svg
  src/assets/img/banner/대구.svg
  src/assets/img/banner/대덕.svg
  src/assets/img/banner/미림.svg
  src/assets/img/banner/부산.svg
  src/components/main/banner/Busan.tsx
  src/components/main/banner/Daeduck.tsx
  src/components/main/banner/Daegu.tsx
  src/components/main/banner/Gwangju.tsx
  src/components/main/banner/Mirim.tsx
  src/components/main/banner/style.ts
  src/components/main/menu/MainMenu/style.ts
  src/components/main/slide/index.tsx
Labels: Chore

#52 🔀:: (#51) 서버값 디자인에 맞게 변환해주는 함수 추가
  src/components/admin/graduationBox.tsx
  src/components/admin/manageReport/reports/comment/index.tsx
  src/components/admin/manageReport/reports/post/index.tsx
  src/components/admin/manageReport/reports/user/index.tsx
  src/components/editProfile/index.tsx
  src/components/follow/followCard.tsx
  src/components/mypage/profile/index.tsx
  src/pages/profile/index.tsx
  src/utils/function/translate/school.ts
  src/utils/function/translate/user_scope.ts
Labels: 기능 추가

#56 🔀:: (#55) seo 처리
  package.json
  public/index.html
  src/SEOMetaTage.tsx
  src/index.tsx
  src/router.tsx
  yarn.lock
Labels: 기능 추가

#60 🔀:: (#59) 졸업생인증 api 연결
  src/components/graduateCheck/graduateCheckForm/index.tsx
  src/hooks/graduateCheck/useGraduateCheck.ts
  src/utils/interface/GraduateCheck.ts
Labels: 기능 추가

#62 🔀:: (#61) 자동 로그인 기능 추가
  src/components/login/index.tsx
  src/components/login/loginForm/index.tsx
  src/components/login/loginForm/style.ts
  src/hooks/login/useLogin.ts
  src/router.tsx
  src/utils/axios/index.ts
Labels: 기능 추가

#64 🔀:: (#63) 카테고리쪽 수정
  public/robots.txt
  src/components/category/constant.ts
  src/components/category/index.tsx
  src/components/common/select/dropdown/options.ts
  src/components/header/category/index.tsx
  src/components/post/constant.ts
  src/components/post/postlist/index.tsx
  src/components/post/postlist/style.ts
  src/models/common.ts
  src/pages/category/CategoryPage.tsx
  src/pages/category/communityCategoryPage.tsx
  src/pages/post/PostListPage.tsx
  src/router.tsx
  src/style/global.ts
Labels: 리펙토링

#68 🔀:: (#67) seo default값 설정
  src/SEOMetaTage.tsx
  src/logo.svg
  src/pages/isMobileAccess.tsx
  src/router.tsx
Labels: Chore

#66 🔀:: (#65) 공지사항 작성 api 추가
  src/components/admin/constant.ts
  src/components/admin/noticeList.tsx
  src/components/admin/writeNotice.tsx
  src/router.tsx
  src/utils/api/notice/index.ts
Labels: Chore, 기능 추가
